package br.com.biosolar.citrus.model;

public enum TipoEvento {
    IRRIGACAO_CRITICA,
    IRRIGACAO_CONCLUIDA,
    PROTECAO_SATURACAO,
    COMANDO_MANUAL,
    COMANDO_RECUSADO,
    BLOQUEIO_EMERGENCIA,
    IRRIGACAO_BLOQUEADA,
    RECUPERACAO_SISTEMA,
    ALERTA_UMIDADE,
    ALERTA_RESERVATORIO,
    RESERVATORIO_ATUALIZADO,
    SIMULACAO,
    CADASTRO,
    SISTEMA
}