-- BioSolar Citrus - schema inicial
-- SQL compativel com PostgreSQL (producao) e H2 em modo PostgreSQL (testes / perfil h2).

-- Talhoes do pomar: estado atual do sensor de umidade e do conjunto motobomba + aspersor
CREATE TABLE talhao (
    id                      VARCHAR(10)      PRIMARY KEY,
    nome                    VARCHAR(60)      NOT NULL,
    cultura                 VARCHAR(20)      NOT NULL,
    variedade               VARCHAR(60)      NOT NULL,
    solo                    VARCHAR(80)      NOT NULL,
    area_ha                 DOUBLE PRECISION NOT NULL,
    plantas                 INTEGER          NOT NULL,
    prioridade              INTEGER          NOT NULL,
    umidade                 DOUBLE PRECISION NOT NULL,
    limite_critico          DOUBLE PRECISION NOT NULL,
    limite_atencao          DOUBLE PRECISION NOT NULL,
    umidade_alvo            DOUBLE PRECISION NOT NULL,
    taxa_evapotranspiracao  DOUBLE PRECISION NOT NULL,
    ganho_irrigacao         DOUBLE PRECISION NOT NULL,
    vazao_bomba_m3h         DOUBLE PRECISION NOT NULL,
    potencia_bomba_kw       DOUBLE PRECISION NOT NULL,
    aspersor_ligado         BOOLEAN          NOT NULL,
    modo_acionamento        VARCHAR(20)      NOT NULL,
    status                  VARCHAR(20)      NOT NULL,
    irrigacao_bloqueada     BOOLEAN          NOT NULL DEFAULT FALSE,
    ultima_atualizacao      TIMESTAMP WITH TIME ZONE NOT NULL,
    ultimo_acionamento      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_talhao_umidade CHECK (umidade BETWEEN 0 AND 100)
);

-- Reservatorio central (linha unica, id = 1)
CREATE TABLE reservatorio (
    id                   INTEGER          PRIMARY KEY,
    nome                 VARCHAR(60)      NOT NULL,
    capacidade_m3        DOUBLE PRECISION NOT NULL,
    nivel                DOUBLE PRECISION NOT NULL,
    limite_atencao       DOUBLE PRECISION NOT NULL,
    limite_critico       DOUBLE PRECISION NOT NULL,
    limite_rearme        DOUBLE PRECISION NOT NULL,
    vazao_recarga_m3h    DOUBLE PRECISION NOT NULL,
    status               VARCHAR(20)      NOT NULL,
    bloqueio_emergencia  BOOLEAN          NOT NULL,
    ultima_atualizacao   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_reservatorio_nivel CHECK (nivel BETWEEN 0 AND 100)
);

-- Estado do simulador (relogio da fazenda, velocidade e acumuladores de energia/agua)
CREATE TABLE estado_simulacao (
    id                      INTEGER          PRIMARY KEY,
    relogio_simulado        TIMESTAMP        NOT NULL,
    fator_velocidade        INTEGER          NOT NULL,
    pausada                 BOOLEAN          NOT NULL,
    ticks                   BIGINT           NOT NULL,
    potencia_solar_pico_kw  DOUBLE PRECISION NOT NULL,
    energia_consumida_kwh   DOUBLE PRECISION NOT NULL,
    energia_solar_kwh       DOUBLE PRECISION NOT NULL,
    agua_consumida_m3       DOUBLE PRECISION NOT NULL,
    iniciada_em             TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Historico de eventos: automacoes, comandos manuais, bloqueios, alertas e recuperacoes
CREATE TABLE evento (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instante            TIMESTAMP WITH TIME ZONE NOT NULL,
    hora_simulada       TIMESTAMP,
    tipo                VARCHAR(40)      NOT NULL,
    severidade          VARCHAR(20)      NOT NULL,
    origem              VARCHAR(20)      NOT NULL,
    regra               VARCHAR(10),
    talhao_id           VARCHAR(10)      REFERENCES talhao (id),
    titulo              VARCHAR(160)     NOT NULL,
    descricao           VARCHAR(600)     NOT NULL,
    nivel_reservatorio  DOUBLE PRECISION
);
CREATE INDEX idx_evento_instante ON evento (instante);
CREATE INDEX idx_evento_tipo ON evento (tipo);

-- Leituras periodicas de telemetria (base dos graficos e do relatorio)
CREATE TABLE leitura_telemetria (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instante             TIMESTAMP WITH TIME ZONE NOT NULL,
    hora_simulada        TIMESTAMP        NOT NULL,
    nivel_reservatorio   DOUBLE PRECISION NOT NULL,
    umidade_media        DOUBLE PRECISION NOT NULL,
    aspersores_ligados   INTEGER          NOT NULL,
    consumo_kw           DOUBLE PRECISION NOT NULL,
    geracao_solar_kw     DOUBLE PRECISION NOT NULL,
    indice               INTEGER          NOT NULL,
    bloqueio_emergencia  BOOLEAN          NOT NULL
);
CREATE INDEX idx_leitura_instante ON leitura_telemetria (instante);

CREATE TABLE leitura_talhao (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leitura_id       BIGINT           NOT NULL REFERENCES leitura_telemetria (id) ON DELETE CASCADE,
    talhao_id        VARCHAR(10)      NOT NULL REFERENCES talhao (id),
    umidade          DOUBLE PRECISION NOT NULL,
    aspersor_ligado  BOOLEAN          NOT NULL
);
CREATE INDEX idx_leitura_talhao_leitura ON leitura_talhao (leitura_id);
